CLIENT_HOST = '0.0.0.0'
SERVER_HOST = '77.73.39.173'
SERVER_PORT = 8081

LIMIT_LISTEN = 2

ENCRYPTED_MESSAGE_SIZE = 1024

CLIENT_NAME = 'Client'
SERVER_NAME = 'Server'
EXIT_MESSAGE = 'exit'

ROUND_BRACKETS = '()'
SQUARE_BRACKETS = '[]'
COMMA = ', '
SPACE = ' '